// <auto-generated />
using System;
using GestionRespuestosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionRepuestosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Permiso", b =>
                {
                    b.Property<Guid>("idPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dataPermiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPermiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.RepuestoVehiculo", b =>
                {
                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("RepuestoId", "VehiculoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RepuestosVehiculos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Rol", b =>
                {
                    b.Property<Guid>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.UsuarioPermiso", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<Guid>("idPermiso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPermiso");

                    b.HasKey("idUsuario", "idPermiso");

                    b.ToTable("UsuariosPermisos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.UsuarioRol", b =>
                {
                    b.Property<int>("idUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<Guid>("idRol")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idRol");

                    b.HasKey("idUsuario", "idRol");

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Repuesto", b =>
                {
                    b.HasOne("GestionRepuestosAPI.Modelos.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionRepuestosAPI.Modelos.Proveedor", null)
                        .WithMany("Repuestos")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.RepuestoVehiculo", b =>
                {
                    b.HasOne("GestionRepuestosAPI.Modelos.Repuesto", "Repuesto")
                        .WithMany("RepuestosVehiculos")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionRepuestosAPI.Modelos.Vehiculo", "Vehiculo")
                        .WithMany("RepuestosVehiculos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repuesto");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Proveedor", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Repuesto", b =>
                {
                    b.Navigation("RepuestosVehiculos");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Modelos.Vehiculo", b =>
                {
                    b.Navigation("RepuestosVehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
